### ISSUE TITLE
App not filling screen for iPhone X

### ISSUE THREAD

**Issue by jrthib** [ionicthemes/ion2fullapp#12]
**Describe the bug**
When running the app on the iPhone X simulator with no modifications, it does not fill the screen. It shows the top and bottom margins as if it's not compatible.

**To Reproduce**
1. Download app source code
2. `ionic cordova emulate ios --target "iPhone-X"`
3. Observe the top and bottom margins

**Expected behavior**
The app should fill the iPhone X screen properly

**Screenshots**
<img width="478" alt="screenshot 2018-06-08 23 39 52" src="https://user-images.githubusercontent.com/750551/41187367-4b2ec3fc-6b75-11e8-9001-d2784b9df811.png">

Thanks :)

**Comment by djabif** [comment]
Thanks for the feedback. 
We will fix it for the next release

**Comment by tiptronic** [comment]
Does that mean you don't check, if the template shows properly on premium devices?

**Comment by djabif** [comment]
Yes, we do check that.
Give me a couple of days and I will send you the steps to make it work. 
Thanks

**Comment by tiptronic** [comment]
Hi - thx for the response. Getting it to work is not the problem, but I had the impression this is a professional quality template, where I do expect these details. If I need to fix the template first, it's a bit pointless. (and the iPhone X is on the market since 8 months 😉 )
I tried your demo on IonicView and (besides it's hardly usable on iPhoneX), it has some more quirks:
e.g. - if you switch the language to spanish, the checkbox in settings switches back to english when you enter setting the next time. So to switch back to english, I first need to set another language and than back to english.
- Transitioning from one page to the other shows a loading indicator, which makes everything look like a webpage.
- Sometimes, if I click on 'Profile', it hangs showing the loading indicator and the only way out is to stripe down with 3 fingers.
- when I enter the main page 'Sports', select a sub-page (e.g. Basketball) and then go back, the 'Popular' carousel shows a horizontal scrollbar (even worse: slightly on top of the round images).
- and there seems not to be an iOS-styling at all
... etc..
Sorry - that's all I could check on the Ionic View app; so I don't know how current this is and if any of the mentioned items are outdated or easy to fix. As is, it's too buggy for me anyway.... I hope you will find some time to fix that... If you do, I'd be happy to provide some more feedback...
andy

**Comment by djabif** [comment]
@tiptronic thank you SO much for your feedback 👍 
Today we have pushed a new version with improvements for Iphone X support.
Also, the other things you mentioned were fixed months ago but the new version wasn't released into ionic view. Sorry for that. 

@jrthib please download the new version from your account on ionicthemes.com to get the fixes for Iphone X.

**Comment by tiptronic** [comment]
@djabif The new version looks *much* better than the one I originally found. There are still some flaws (e.g. you can drag the onboarding screens diagonally and there's still the tiny scrollbar showing in the rounded slider), but overall it looks quite good.
What I haven't seen: It runs on the iPhone in Material Design. Is there an option to switch to default iOS design? (For me the fonts are way to small as is... a proper styling could help here).
Good job, anyway!
